from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from scripts.pytest_metadata import read_pytest_metadata


BUILD_INFO = Path("build_info.json")

REPOSITORY = "jay-a/granular-rves"
AUTHOR = "Jay M. Appleton"
STATUS = "Early development"


def get_source_commit() -> str:
    """Return the short Git commit hash for the current source state.

    Returns
    -------
    str
        The seven-character Git commit hash associated with the
        checked-out source tree.

    Raises
    ------
    RuntimeError
        If the current Git commit cannot be determined.
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=7", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(
            "Unable to determine the current source commit."
        ) from exc

    return result.stdout.strip()


def generate_build_info(
    output: Path,
    pytest_xml: Path,
    build_status: str = "passed",
) -> None:
    """Generate repository build metadata.

    Parameters
    ----------
    output
        Path where ``build_info.json`` will be written.
    pytest_xml
        Path to the JUnit XML report generated by pytest.
    build_status
        Status of the documentation and report build.

    Raises
    ------
    FileNotFoundError
        If the pytest JUnit XML report does not exist.
    ValueError
        If the pytest report contains invalid test counts.
    """
    test_metadata = read_pytest_metadata(pytest_xml)

    build_info = {
        "repository": REPOSITORY,
        "source_commit": get_source_commit(),
        "generated": datetime.now(timezone.utc).isoformat(),
        "author": AUTHOR,
        "status": STATUS,
        "tests_passed": test_metadata["tests_passed"],
        "tests_total": test_metadata["tests_total"],
        "build": build_status,
    }

    output.parent.mkdir(parents=True, exist_ok=True)

    output.write_text(
        json.dumps(build_info, indent=2) + "\n",
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Generate build metadata for the project report."
    )

    parser.add_argument(
        "--pytest-xml",
        type=Path,
        required=True,
        help="Path to the pytest JUnit XML report.",
    )

    parser.add_argument(
        "--build-status",
        default="passed",
        help="Status of the documentation/report build.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=BUILD_INFO,
        help="Path for the generated build metadata JSON.",
    )

    return parser.parse_args()


def main() -> None:
    """Generate build metadata from pytest results."""
    args = parse_args()

    generate_build_info(
        output=args.output,
        pytest_xml=args.pytest_xml,
        build_status=args.build_status,
    )


if __name__ == "__main__":
    main()
