from __future__ import annotations

import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET


def read_pytest_metadata(
    junitxml_path: Path,
) -> dict[str, int]:
    """Read test counts from a pytest JUnit XML report.

    Parameters
    ----------
    junitxml_path
        Path to the JUnit XML file generated by pytest.

    Returns
    -------
    dict[str, int]
        Dictionary containing ``tests_total`` and ``tests_passed``.

    Raises
    ------
    FileNotFoundError
        If the JUnit XML file does not exist.
    ValueError
        If the XML report does not contain valid test counts.
    """
    if not junitxml_path.exists():
        raise FileNotFoundError(
            f"JUnit XML report not found: {junitxml_path}"
        )

    root = ET.parse(junitxml_path).getroot()

    tests_total = 0
    failures = 0
    errors = 0
    skipped = 0

    test_suites = (
        [root]
        if root.tag == "testsuite"
        else root.findall("testsuite")
    )

    for suite in test_suites:
        tests_total += int(suite.attrib.get("tests", 0))
        failures += int(suite.attrib.get("failures", 0))
        errors += int(suite.attrib.get("errors", 0))
        skipped += int(suite.attrib.get("skipped", 0))

    tests_passed = (
        tests_total
        - failures
        - errors
        - skipped
    )

    if tests_total < 0 or tests_passed < 0:
        raise ValueError("Invalid test counts in JUnit XML report.")

    return {
        "tests_passed": tests_passed,
        "tests_total": tests_total,
    }


def main() -> None:
    """Read pytest JUnit XML and write test metadata as JSON."""
    parser = argparse.ArgumentParser(
        description="Read test counts from a pytest JUnit XML report."
    )

    parser.add_argument(
        "junitxml",
        type=Path,
        help="Path to the pytest JUnit XML report.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        help="Optional path for the JSON metadata output.",
    )

    args = parser.parse_args()

    metadata = read_pytest_metadata(args.junitxml)

    if args.output is None:
        print(json.dumps(metadata, indent=2))
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)

    args.output.write_text(
        json.dumps(metadata, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
